CREATE DATABASE 

USE horusOps;

CREATE TABLE SUCURSALES (
    ID_SUCURSAL                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_SUCURSAL            VARCHAR(100) NOT NULL,
    DIRECCION_SUCURSAL         VARCHAR(200) NOT NULL,
    CIUDAD                     VARCHAR(100),
    ACTIVO                     BIT NOT NULL DEFAULT 1,
    FECHA_ALTA                 DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_EMPLEADO            VARCHAR(100) NOT NULL,
    APELLIDO_EMPLEADO          VARCHAR(100) NOT NULL,
    DNI_EMPLEADO                VARCHAR(20) NOT NULL UNIQUE,
    EMAIL_EMPLEADO              VARCHAR(150) NOT NULL UNIQUE,
    TELEFONO_EMPLEADO           VARCHAR(30),
    FECHA_INGRESO               DATE NOT NULL,
    ID_SUCURSAL                 INT NOT NULL,
    ACTIVO                      BIT NOT NULL DEFAULT 1,
    FECHA_ALTA                  DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_EMPLEADOS_SUCURSALES
        FOREIGN KEY(ID_SUCURSAL)
        REFERENCES SUCURSALES(ID_SUCURSAL) 
);

CREATE TABLE CLIENTES (
    ID_CLIENTE                 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DNI_CLIENTE                VARCHAR(20) NOT NULL UNIQUE,
    NOMBRE_CLIENTE             VARCHAR(150) NOT NULL,
    DIRECCION_ENVIO_CLIENTE    VARCHAR(200),
    EMAIL_CLIENTE              VARCHAR(150),
    TELEFONO_CLIENTE           VARCHAR(30),
    FECHA_ALTA                 DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_PRODUCTO            VARCHAR(100) NOT NULL,
    PRECIO_PRODUCTO            DECIMAL(10,2) NOT NULL,
    ACTIVO                     BIT NOT NULL DEFAULT 1
);

CREATE TABLE VENTAS (
    ID_VENTA                       INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FECHA_VENTA                    DATETIME NOT NULL DEFAULT GETDATE(),

    ID_CLIENTE                     INT NOT NULL,
    ID_EMPLEADO                    INT NOT NULL,
    ID_SUCURSAL                    INT NOT NULL,

    DNI_CLIENTE                    VARCHAR(20) NOT NULL,
    NOMBRE_CLIENTE                 VARCHAR(150) NOT NULL,
    DIRECCION_ENVIO_CLIENTE        VARCHAR(200),

    NOMBRE_EMPLEADO                VARCHAR(100) NOT NULL,

    NOMBRE_SUCURSAL_VENTA          VARCHAR(100) NOT NULL,
    DIRECCION_SUCURSAL_VENTA       VARCHAR(200) NOT NULL,

    IMPORTE_TOTAL                  DECIMAL(10,2) NOT NULL,

    CONSTRAINT FK_VENTAS_CLIENTES
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE),

    CONSTRAINT FK_VENTAS_EMPLEADOS
        FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADOS (ID_EMPLEADO),

    CONSTRAINT FK_VENTAS_SUCURSALES
        FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSALES(ID_SUCURSAL)
);

CREATE TABLE DETALLE_VENTAS(
    ID_DETALLE_VENTA        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_VENTA                INT NOT NULL,
    ID_PRODUCTO             INT NOT NULL,

    PRODUCTO                VARCHAR(100) NOT NULL,

    CANTIDAD                INT NOT NULL,
    PRECIO_UNITARIO         DECIMAL(10,2) NOT NULL

    CONSTRAINT FK_DETALLE_VENTAS_VENTAS
        FOREIGN KEY(ID_VENTA)
        REFERENCES VENTAS(ID_VENTA),

    CONSTRAINT FK_DETALLE_VENTAS_PRODUCTOS
        FOREIGN KEY(ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PROCESOS(
    ID_PROCESO              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_PROCESO          VARCHAR(100) NOT NULL,
    DESCRIPCION_PROCESO     VARCHAR(300),
    EXPRESION_CRON          VARCHAR(50),
    PROBABILIDAD_ERROR      DECIMAL(5,2) NOT NULL DEFAULT 0,
    ACTIVO                  BIT NOT NULL DEFAULT 1,
    FECHA_ALTA              DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE EJECUCIONES_PROCESOS (
    ID_EJECUCION            BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_PROCESO              INT NOT NULL,
    FECHA_INICIO            DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_FIN               DATETIME,
    ESTADO_EJECUCION        VARCHAR(20) NOT NULL,
    REGISTROS_PROCESADOS    INT NOT NULL DEFAULT 0,
    CANTIDAD_ERRORES        INT NOT NULL DEFAULT 0,

    CONSTRAINT FK_EJECUCIONES_PROCESOS
        FOREIGN KEY(ID_PROCESO)
        REFERENCES PROCESOS(ID_PROCESO)
);

CREATE TABLE LOGS_PROCESOS(
    ID_LOG                  BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_EJECUCION            BIGINT NOT NULL,
    FECHA_LOG               DATETIME NOT NULL DEFAULT GETDATE(),
    NIVEL_LOG               VARCHAR(20) NOT NULL,
    MENSAJE_LOG             VARCHAR(2000) NOT NULL,
    DETALLE_ERROR           VARCHAR(MAX),

    CONSTRAINT FK_LOGS_EJECUCIONES
        FOREIGN KEY(ID_EJECUCION)
        REFERENCES EJECUCIONES_PROCESOS(ID_EJECUCION)
);

CREATE TABLE USUARIOS (
    ID_USUARIO              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_USUARIO          VARCHAR(50) NOT NULL UNIQUE,
    CLAVE_HASH              VARCHAR(500) NOT NULL,
    ROL_USUARIO             VARCHAR(30) NOT NULL,
    ID_EMPLEADO             INT UNIQUE,
    ACTIVO                  BIT NOT NULL DEFAULT 1,
    FECHA_ALTA              DATETIME NOT NULL DEFAULT GETDATE()

    CONSTRAINT FK_USUARIOS_EMPLEADOS
        FOREIGN KEY(ID_EMPLEADO)
        REFERENCES EMPLEADOS (ID_EMPLEADO)
);